### ISSUE TITLE
the code is been detect by gmail acct now, can't log in

### ISSUE THREAD

**Issue by sandou78** [dpw1/puppeteer-gmail#1]

**Comment by dpw1** [comment]
Hi @sandou78 ,

I've double checked and yes, unfortunately it's outdated now. I'll update the readme soon. Thank you for the heads up!

EDIT: Anyhow, alternatively, you can check out [UI Vision RPA](https://chrome.google.com/webstore/detail/uivision-rpa/gcbalfbdmfieckjlnblleoemohcganoc), I'd say they're better than Puppeteer for this sort of scenario.

**Comment by sandou78** [comment]
I found use puputeer stealth 2 4.5 it works .Give a try

**Comment by dpw1** [comment]
Glad to hear that!
